// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-XLppPS9B7ia-pcPahedCCk-as85JVBo',
    appId: '1:199993499194:web:fd93cb3bbec4bde5d1df03',
    messagingSenderId: '199993499194',
    projectId: 'krishi-sahayak-190a1',
    authDomain: 'krishi-sahayak-190a1.firebaseapp.com',
    storageBucket: 'krishi-sahayak-190a1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKxElFK_jHD2qFXCJC9GJIzkeLaABgbP4',
    appId: '1:199993499194:android:2f033f154091f21cd1df03',
    messagingSenderId: '199993499194',
    projectId: 'krishi-sahayak-190a1',
    storageBucket: 'krishi-sahayak-190a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3VI1XBYVH_2MYbPTiAB_xz_txwBkBiS0',
    appId: '1:199993499194:ios:12185a3c96e73e72d1df03',
    messagingSenderId: '199993499194',
    projectId: 'krishi-sahayak-190a1',
    storageBucket: 'krishi-sahayak-190a1.appspot.com',
    androidClientId: '199993499194-e80971h361sdgiuo7pvltm9ug8bav6ab.apps.googleusercontent.com',
    iosClientId: '199993499194-b16clr8l4has63ub7fvdp45u81i8v9d4.apps.googleusercontent.com',
    iosBundleId: 'com.example.krishiSahayak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3VI1XBYVH_2MYbPTiAB_xz_txwBkBiS0',
    appId: '1:199993499194:ios:9a9d8b72ad574bf7d1df03',
    messagingSenderId: '199993499194',
    projectId: 'krishi-sahayak-190a1',
    storageBucket: 'krishi-sahayak-190a1.appspot.com',
    androidClientId: '199993499194-e80971h361sdgiuo7pvltm9ug8bav6ab.apps.googleusercontent.com',
    iosClientId: '199993499194-q2ee885cjem92hjgqe7nbhti3gl08bes.apps.googleusercontent.com',
    iosBundleId: 'com.example.krishiSahayak.RunnerTests',
  );
}
